<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Country;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Country::upsert([
            ['code' => 'AF', 'name' => 'Afghanistan', 'phone_code' => '+93', 'is_active' => true],
            ['code' => 'AL', 'name' => 'Albania', 'phone_code' => '+355', 'is_active' => true],
            ['code' => 'DZ', 'name' => 'Algeria', 'phone_code' => '+213', 'is_active' => true],
            ['code' => 'AD', 'name' => 'Andorra', 'phone_code' => '+376', 'is_active' => true],
            ['code' => 'AO', 'name' => 'Angola', 'phone_code' => '+244', 'is_active' => true],
            ['code' => 'AG', 'name' => 'Antigua and Barbuda', 'phone_code' => '+1-268', 'is_active' => true],
            ['code' => 'AR', 'name' => 'Argentina', 'phone_code' => '+54', 'is_active' => true],
            ['code' => 'AM', 'name' => 'Armenia', 'phone_code' => '+374', 'is_active' => true],
            ['code' => 'AU', 'name' => 'Australia', 'phone_code' => '+61', 'is_active' => true],
            ['code' => 'AT', 'name' => 'Austria', 'phone_code' => '+43', 'is_active' => true],
            ['code' => 'AZ', 'name' => 'Azerbaijan', 'phone_code' => '+994', 'is_active' => true],
            ['code' => 'BS', 'name' => 'Bahamas', 'phone_code' => '+1-242', 'is_active' => true],
            ['code' => 'BH', 'name' => 'Bahrain', 'phone_code' => '+973', 'is_active' => true],
            ['code' => 'BD', 'name' => 'Bangladesh', 'phone_code' => '+880', 'is_active' => true],
            ['code' => 'BB', 'name' => 'Barbados', 'phone_code' => '+1-246', 'is_active' => true],
            ['code' => 'BY', 'name' => 'Belarus', 'phone_code' => '+375', 'is_active' => true],
            ['code' => 'BE', 'name' => 'Belgium', 'phone_code' => '+32', 'is_active' => true],
            ['code' => 'BZ', 'name' => 'Belize', 'phone_code' => '+501', 'is_active' => true],
            ['code' => 'BJ', 'name' => 'Benin', 'phone_code' => '+229', 'is_active' => true],
            ['code' => 'BT', 'name' => 'Bhutan', 'phone_code' => '+975', 'is_active' => true],
            ['code' => 'BO', 'name' => 'Bolivia', 'phone_code' => '+591', 'is_active' => true],
            ['code' => 'BA', 'name' => 'Bosnia and Herzegovina', 'phone_code' => '+387', 'is_active' => true],
            ['code' => 'BW', 'name' => 'Botswana', 'phone_code' => '+267', 'is_active' => true],
            ['code' => 'BR', 'name' => 'Brazil', 'phone_code' => '+55', 'is_active' => true],
            ['code' => 'BN', 'name' => 'Brunei', 'phone_code' => '+673', 'is_active' => true],
            ['code' => 'BG', 'name' => 'Bulgaria', 'phone_code' => '+359', 'is_active' => true],
            ['code' => 'BF', 'name' => 'Burkina Faso', 'phone_code' => '+226', 'is_active' => true],
            ['code' => 'BI', 'name' => 'Burundi', 'phone_code' => '+257', 'is_active' => true],
            ['code' => 'CV', 'name' => 'Cabo Verde', 'phone_code' => '+238', 'is_active' => true],
            ['code' => 'KH', 'name' => 'Cambodia', 'phone_code' => '+855', 'is_active' => true],
            ['code' => 'CM', 'name' => 'Cameroon', 'phone_code' => '+237', 'is_active' => true],
            ['code' => 'CA', 'name' => 'Canada', 'phone_code' => '+1', 'is_active' => true],
            ['code' => 'CF', 'name' => 'Central African Republic', 'phone_code' => '+236', 'is_active' => true],
            ['code' => 'TD', 'name' => 'Chad', 'phone_code' => '+235', 'is_active' => true],
            ['code' => 'CL', 'name' => 'Chile', 'phone_code' => '+56', 'is_active' => true],
            ['code' => 'CN', 'name' => 'China', 'phone_code' => '+86', 'is_active' => true],
            ['code' => 'CO', 'name' => 'Colombia', 'phone_code' => '+57', 'is_active' => true],
            ['code' => 'KM', 'name' => 'Comoros', 'phone_code' => '+269', 'is_active' => true],
            ['code' => 'CG', 'name' => 'Congo', 'phone_code' => '+242', 'is_active' => true],
            ['code' => 'CD', 'name' => 'Democratic Republic of the Congo', 'phone_code' => '+243', 'is_active' => true],
            ['code' => 'CR', 'name' => 'Costa Rica', 'phone_code' => '+506', 'is_active' => true],
            ['code' => 'CI', 'name' => "Côte d'Ivoire", 'phone_code' => '+225', 'is_active' => true],
            ['code' => 'HR', 'name' => 'Croatia', 'phone_code' => '+385', 'is_active' => true],
            ['code' => 'CU', 'name' => 'Cuba', 'phone_code' => '+53', 'is_active' => true],
            ['code' => 'CY', 'name' => 'Cyprus', 'phone_code' => '+357', 'is_active' => true],
            ['code' => 'CZ', 'name' => 'Czechia', 'phone_code' => '+420', 'is_active' => true],
            ['code' => 'DK', 'name' => 'Denmark', 'phone_code' => '+45', 'is_active' => true],
            ['code' => 'DJ', 'name' => 'Djibouti', 'phone_code' => '+253', 'is_active' => true],
            ['code' => 'DM', 'name' => 'Dominica', 'phone_code' => '+1-767', 'is_active' => true],
            ['code' => 'DO', 'name' => 'Dominican Republic', 'phone_code' => '+1-809', 'is_active' => true],
            ['code' => 'EC', 'name' => 'Ecuador', 'phone_code' => '+593', 'is_active' => true],
            ['code' => 'EG', 'name' => 'Egypt', 'phone_code' => '+20', 'is_active' => true],
            ['code' => 'SV', 'name' => 'El Salvador', 'phone_code' => '+503', 'is_active' => true],
            ['code' => 'GQ', 'name' => 'Equatorial Guinea', 'phone_code' => '+240', 'is_active' => true],
            ['code' => 'ER', 'name' => 'Eritrea', 'phone_code' => '+291', 'is_active' => true],
            ['code' => 'EE', 'name' => 'Estonia', 'phone_code' => '+372', 'is_active' => true],
            ['code' => 'SZ', 'name' => 'Eswatini', 'phone_code' => '+268', 'is_active' => true],
            ['code' => 'ET', 'name' => 'Ethiopia', 'phone_code' => '+251', 'is_active' => true],
            ['code' => 'FJ', 'name' => 'Fiji', 'phone_code' => '+679', 'is_active' => true],
            ['code' => 'FI', 'name' => 'Finland', 'phone_code' => '+358', 'is_active' => true],
            ['code' => 'FR', 'name' => 'France', 'phone_code' => '+33', 'is_active' => true],
            ['code' => 'GA', 'name' => 'Gabon', 'phone_code' => '+241', 'is_active' => true],
            ['code' => 'GM', 'name' => 'Gambia', 'phone_code' => '+220', 'is_active' => true],
            ['code' => 'GE', 'name' => 'Georgia', 'phone_code' => '+995', 'is_active' => true],
            ['code' => 'DE', 'name' => 'Germany', 'phone_code' => '+49', 'is_active' => true],
            ['code' => 'GH', 'name' => 'Ghana', 'phone_code' => '+233', 'is_active' => true],
            ['code' => 'GR', 'name' => 'Greece', 'phone_code' => '+30', 'is_active' => true],
            ['code' => 'GD', 'name' => 'Grenada', 'phone_code' => '+1-473', 'is_active' => true],
            ['code' => 'GT', 'name' => 'Guatemala', 'phone_code' => '+502', 'is_active' => true],
            ['code' => 'GN', 'name' => 'Guinea', 'phone_code' => '+224', 'is_active' => true],
            ['code' => 'GW', 'name' => 'Guinea-Bissau', 'phone_code' => '+245', 'is_active' => true],
            ['code' => 'GY', 'name' => 'Guyana', 'phone_code' => '+592', 'is_active' => true],
            ['code' => 'HT', 'name' => 'Haiti', 'phone_code' => '+509', 'is_active' => true],
            ['code' => 'HN', 'name' => 'Honduras', 'phone_code' => '+504', 'is_active' => true],
            ['code' => 'HU', 'name' => 'Hungary', 'phone_code' => '+36', 'is_active' => true],
            ['code' => 'IS', 'name' => 'Iceland', 'phone_code' => '+354', 'is_active' => true],
            ['code' => 'IN', 'name' => 'India', 'phone_code' => '+91', 'is_active' => true],
            ['code' => 'ID', 'name' => 'Indonesia', 'phone_code' => '+62', 'is_active' => true],
            ['code' => 'IR', 'name' => 'Iran', 'phone_code' => '+98', 'is_active' => true],
            ['code' => 'IQ', 'name' => 'Iraq', 'phone_code' => '+964', 'is_active' => true],
            ['code' => 'IE', 'name' => 'Ireland', 'phone_code' => '+353', 'is_active' => true],
            ['code' => 'IL', 'name' => 'Israel', 'phone_code' => '+972', 'is_active' => true],
            ['code' => 'IT', 'name' => 'Italy', 'phone_code' => '+39', 'is_active' => true],
            ['code' => 'JM', 'name' => 'Jamaica', 'phone_code' => '+1-876', 'is_active' => true],
            ['code' => 'JP', 'name' => 'Japan', 'phone_code' => '+81', 'is_active' => true],
            ['code' => 'JO', 'name' => 'Jordan', 'phone_code' => '+962', 'is_active' => true],
            ['code' => 'KZ', 'name' => 'Kazakhstan', 'phone_code' => '+7', 'is_active' => true],
            ['code' => 'KE', 'name' => 'Kenya', 'phone_code' => '+254', 'is_active' => true],
            ['code' => 'KI', 'name' => 'Kiribati', 'phone_code' => '+686', 'is_active' => true],
            ['code' => 'KP', 'name' => 'North Korea', 'phone_code' => '+850', 'is_active' => true],
            ['code' => 'KR', 'name' => 'South Korea', 'phone_code' => '+82', 'is_active' => true],
            ['code' => 'KW', 'name' => 'Kuwait', 'phone_code' => '+965', 'is_active' => true],
            ['code' => 'KG', 'name' => 'Kyrgyzstan', 'phone_code' => '+996', 'is_active' => true],
            ['code' => 'LA', 'name' => 'Laos', 'phone_code' => '+856', 'is_active' => true],
            ['code' => 'LV', 'name' => 'Latvia', 'phone_code' => '+371', 'is_active' => true],
            ['code' => 'LB', 'name' => 'Lebanon', 'phone_code' => '+961', 'is_active' => true],
            ['code' => 'LS', 'name' => 'Lesotho', 'phone_code' => '+266', 'is_active' => true],
            ['code' => 'LR', 'name' => 'Liberia', 'phone_code' => '+231', 'is_active' => true],
            ['code' => 'LY', 'name' => 'Libya', 'phone_code' => '+218', 'is_active' => true],
            ['code' => 'LI', 'name' => 'Liechtenstein', 'phone_code' => '+423', 'is_active' => true],
            ['code' => 'LT', 'name' => 'Lithuania', 'phone_code' => '+370', 'is_active' => true],
            ['code' => 'LU', 'name' => 'Luxembourg', 'phone_code' => '+352', 'is_active' => true],
            ['code' => 'MG', 'name' => 'Madagascar', 'phone_code' => '+261', 'is_active' => true],
            ['code' => 'MW', 'name' => 'Malawi', 'phone_code' => '+265', 'is_active' => true],
            ['code' => 'MY', 'name' => 'Malaysia', 'phone_code' => '+60', 'is_active' => true],
            ['code' => 'MV', 'name' => 'Maldives', 'phone_code' => '+960', 'is_active' => true],
            ['code' => 'ML', 'name' => 'Mali', 'phone_code' => '+223', 'is_active' => true],
            ['code' => 'MT', 'name' => 'Malta', 'phone_code' => '+356', 'is_active' => true],
            ['code' => 'MH', 'name' => 'Marshall Islands', 'phone_code' => '+692', 'is_active' => true],
            ['code' => 'MR', 'name' => 'Mauritania', 'phone_code' => '+222', 'is_active' => true],
            ['code' => 'MU', 'name' => 'Mauritius', 'phone_code' => '+230', 'is_active' => true],
            ['code' => 'MX', 'name' => 'Mexico', 'phone_code' => '+52', 'is_active' => true],
            ['code' => 'FM', 'name' => 'Micronesia', 'phone_code' => '+691', 'is_active' => true],
            ['code' => 'MD', 'name' => 'Moldova', 'phone_code' => '+373', 'is_active' => true],
            ['code' => 'MC', 'name' => 'Monaco', 'phone_code' => '+377', 'is_active' => true],
            ['code' => 'MN', 'name' => 'Mongolia', 'phone_code' => '+976', 'is_active' => true],
            ['code' => 'ME', 'name' => 'Montenegro', 'phone_code' => '+382', 'is_active' => true],
            ['code' => 'MA', 'name' => 'Morocco', 'phone_code' => '+212', 'is_active' => true],
            ['code' => 'MZ', 'name' => 'Mozambique', 'phone_code' => '+258', 'is_active' => true],
            ['code' => 'MM', 'name' => 'Myanmar', 'phone_code' => '+95', 'is_active' => true],
            ['code' => 'NA', 'name' => 'Namibia', 'phone_code' => '+264', 'is_active' => true],
            ['code' => 'NR', 'name' => 'Nauru', 'phone_code' => '+674', 'is_active' => true],
            ['code' => 'NP', 'name' => 'Nepal', 'phone_code' => '+977', 'is_active' => true],
            ['code' => 'NL', 'name' => 'Netherlands', 'phone_code' => '+31', 'is_active' => true],
            ['code' => 'NZ', 'name' => 'New Zealand', 'phone_code' => '+64', 'is_active' => true],
            ['code' => 'NI', 'name' => 'Nicaragua', 'phone_code' => '+505', 'is_active' => true],
            ['code' => 'NE', 'name' => 'Niger', 'phone_code' => '+227', 'is_active' => true],
            ['code' => 'NG', 'name' => 'Nigeria', 'phone_code' => '+234', 'is_active' => true],
            ['code' => 'MK', 'name' => 'North Macedonia', 'phone_code' => '+389', 'is_active' => true],
            ['code' => 'NO', 'name' => 'Norway', 'phone_code' => '+47', 'is_active' => true],
            ['code' => 'OM', 'name' => 'Oman', 'phone_code' => '+968', 'is_active' => true],
            ['code' => 'PK', 'name' => 'Pakistan', 'phone_code' => '+92', 'is_active' => true],
            ['code' => 'PW', 'name' => 'Palau', 'phone_code' => '+680', 'is_active' => true],
            ['code' => 'PA', 'name' => 'Panama', 'phone_code' => '+507', 'is_active' => true],
            ['code' => 'PG', 'name' => 'Papua New Guinea', 'phone_code' => '+675', 'is_active' => true],
            ['code' => 'PY', 'name' => 'Paraguay', 'phone_code' => '+595', 'is_active' => true],
            ['code' => 'PE', 'name' => 'Peru', 'phone_code' => '+51', 'is_active' => true],
            ['code' => 'PH', 'name' => 'Philippines', 'phone_code' => '+63', 'is_active' => true],
            ['code' => 'PL', 'name' => 'Poland', 'phone_code' => '+48', 'is_active' => true],
            ['code' => 'PT', 'name' => 'Portugal', 'phone_code' => '+351', 'is_active' => true],
            ['code' => 'QA', 'name' => 'Qatar', 'phone_code' => '+974', 'is_active' => true],
            ['code' => 'RO', 'name' => 'Romania', 'phone_code' => '+40', 'is_active' => true],
            ['code' => 'RU', 'name' => 'Russia', 'phone_code' => '+7', 'is_active' => true],
            ['code' => 'RW', 'name' => 'Rwanda', 'phone_code' => '+250', 'is_active' => true],
            ['code' => 'KN', 'name' => 'Saint Kitts and Nevis', 'phone_code' => '+1-869', 'is_active' => true],
            ['code' => 'LC', 'name' => 'Saint Lucia', 'phone_code' => '+1-758', 'is_active' => true],
            ['code' => 'VC', 'name' => 'Saint Vincent and the Grenadines', 'phone_code' => '+1-784', 'is_active' => true],
            ['code' => 'WS', 'name' => 'Samoa', 'phone_code' => '+685', 'is_active' => true],
            ['code' => 'SM', 'name' => 'San Marino', 'phone_code' => '+378', 'is_active' => true],
            ['code' => 'ST', 'name' => 'Sao Tome and Principe', 'phone_code' => '+239', 'is_active' => true],
            ['code' => 'SA', 'name' => 'Saudi Arabia', 'phone_code' => '+966', 'is_active' => true],
            ['code' => 'SN', 'name' => 'Senegal', 'phone_code' => '+221', 'is_active' => true],
            ['code' => 'RS', 'name' => 'Serbia', 'phone_code' => '+381', 'is_active' => true],
            ['code' => 'SC', 'name' => 'Seychelles', 'phone_code' => '+248', 'is_active' => true],
            ['code' => 'SL', 'name' => 'Sierra Leone', 'phone_code' => '+232', 'is_active' => true],
            ['code' => 'SG', 'name' => 'Singapore', 'phone_code' => '+65', 'is_active' => true],
            ['code' => 'SK', 'name' => 'Slovakia', 'phone_code' => '+421', 'is_active' => true],
            ['code' => 'SI', 'name' => 'Slovenia', 'phone_code' => '+386', 'is_active' => true],
            ['code' => 'SB', 'name' => 'Solomon Islands', 'phone_code' => '+677', 'is_active' => true],
            ['code' => 'SO', 'name' => 'Somalia', 'phone_code' => '+252', 'is_active' => true],
            ['code' => 'ZA', 'name' => 'South Africa', 'phone_code' => '+27', 'is_active' => true],
            ['code' => 'SS', 'name' => 'South Sudan', 'phone_code' => '+211', 'is_active' => true],
            ['code' => 'ES', 'name' => 'Spain', 'phone_code' => '+34', 'is_active' => true],
            ['code' => 'LK', 'name' => 'Sri Lanka', 'phone_code' => '+94', 'is_active' => true],
            ['code' => 'SD', 'name' => 'Sudan', 'phone_code' => '+249', 'is_active' => true],
            ['code' => 'SR', 'name' => 'Suriname', 'phone_code' => '+597', 'is_active' => true],
            ['code' => 'SE', 'name' => 'Sweden', 'phone_code' => '+46', 'is_active' => true],
            ['code' => 'CH', 'name' => 'Switzerland', 'phone_code' => '+41', 'is_active' => true],
            ['code' => 'SY', 'name' => 'Syria', 'phone_code' => '+963', 'is_active' => true],
            ['code' => 'TW', 'name' => 'Taiwan', 'phone_code' => '+886', 'is_active' => true],
            ['code' => 'TJ', 'name' => 'Tajikistan', 'phone_code' => '+992', 'is_active' => true],
            ['code' => 'TZ', 'name' => 'Tanzania', 'phone_code' => '+255', 'is_active' => true],
            ['code' => 'TH', 'name' => 'Thailand', 'phone_code' => '+66', 'is_active' => true],
            ['code' => 'TL', 'name' => 'Timor-Leste', 'phone_code' => '+670', 'is_active' => true],
            ['code' => 'TG', 'name' => 'Togo', 'phone_code' => '+228', 'is_active' => true],
            ['code' => 'TO', 'name' => 'Tonga', 'phone_code' => '+676', 'is_active' => true],
            ['code' => 'TT', 'name' => 'Trinidad and Tobago', 'phone_code' => '+1-868', 'is_active' => true],
            ['code' => 'TN', 'name' => 'Tunisia', 'phone_code' => '+216', 'is_active' => true],
            ['code' => 'TR', 'name' => 'Turkey', 'phone_code' => '+90', 'is_active' => true],
            ['code' => 'TM', 'name' => 'Turkmenistan', 'phone_code' => '+993', 'is_active' => true],
            ['code' => 'TV', 'name' => 'Tuvalu', 'phone_code' => '+688', 'is_active' => true],
            ['code' => 'UG', 'name' => 'Uganda', 'phone_code' => '+256', 'is_active' => true],
            ['code' => 'UA', 'name' => 'Ukraine', 'phone_code' => '+380', 'is_active' => true],
            ['code' => 'AE', 'name' => 'United Arab Emirates', 'phone_code' => '+971', 'is_active' => true],
            ['code' => 'GB', 'name' => 'United Kingdom', 'phone_code' => '+44', 'is_active' => true],
            ['code' => 'US', 'name' => 'United States', 'phone_code' => '+1', 'is_active' => true],
            ['code' => 'UY', 'name' => 'Uruguay', 'phone_code' => '+598', 'is_active' => true],
            ['code' => 'UZ', 'name' => 'Uzbekistan', 'phone_code' => '+998', 'is_active' => true],
            ['code' => 'VU', 'name' => 'Vanuatu', 'phone_code' => '+678', 'is_active' => true],
            ['code' => 'VA', 'name' => 'Vatican City', 'phone_code' => '+39', 'is_active' => true],
            ['code' => 'VE', 'name' => 'Venezuela', 'phone_code' => '+58', 'is_active' => true],
            ['code' => 'VN', 'name' => 'Vietnam', 'phone_code' => '+84', 'is_active' => true],
            ['code' => 'YE', 'name' => 'Yemen', 'phone_code' => '+967', 'is_active' => true],
            ['code' => 'ZM', 'name' => 'Zambia', 'phone_code' => '+260', 'is_active' => true],
            ['code' => 'ZW', 'name' => 'Zimbabwe', 'phone_code' => '+263', 'is_active' => true],
            ], ['code'], ['name', 'phone_code', 'is_active']);
        }
}
