<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CurrencySeeder extends Seeder
{
    public function run(): void
    {
        $currencies = [
            ['country_code' => 'AF', 'country_name' => 'Afghanistan', 'currency_code' => 'AFN', 'currency_name' => 'Afghan Afghani', 'symbol' => '؋'],
            ['country_code' => 'AL', 'country_name' => 'Albania', 'currency_code' => 'ALL', 'currency_name' => 'Albanian Lek', 'symbol' => 'L'],
            ['country_code' => 'DZ', 'country_name' => 'Algeria', 'currency_code' => 'DZD', 'currency_name' => 'Algerian Dinar', 'symbol' => 'دج'],
            ['country_code' => 'AD', 'country_name' => 'Andorra', 'currency_code' => 'EUR', 'currency_name' => 'Euro', 'symbol' => '€'],
            ['country_code' => 'AO', 'country_name' => 'Angola', 'currency_code' => 'AOA', 'currency_name' => 'Angolan Kwanza', 'symbol' => 'Kz'],
            ['country_code' => 'AG', 'country_name' => 'Antigua and Barbuda', 'currency_code' => 'XCD', 'currency_name' => 'East Caribbean Dollar', 'symbol' => '$'],
            ['country_code' => 'AR', 'country_name' => 'Argentina', 'currency_code' => 'ARS', 'currency_name' => 'Argentine Peso', 'symbol' => '$'],
            ['country_code' => 'AM', 'country_name' => 'Armenia', 'currency_code' => 'AMD', 'currency_name' => 'Armenian Dram', 'symbol' => '֏'],
            ['country_code' => 'AU', 'country_name' => 'Australia', 'currency_code' => 'AUD', 'currency_name' => 'Australian Dollar', 'symbol' => '$'],
            ['country_code' => 'AT', 'country_name' => 'Austria', 'currency_code' => 'EUR', 'currency_name' => 'Euro', 'symbol' => '€'],
            ['country_code' => 'AZ', 'country_name' => 'Azerbaijan', 'currency_code' => 'AZN', 'currency_name' => 'Azerbaijani Manat', 'symbol' => '₼'],

            ['country_code' => 'BS', 'country_name' => 'Bahamas', 'currency_code' => 'BSD', 'currency_name' => 'Bahamian Dollar', 'symbol' => '$'],
            ['country_code' => 'BH', 'country_name' => 'Bahrain', 'currency_code' => 'BHD', 'currency_name' => 'Bahraini Dinar', 'symbol' => '.د.ب'],
            ['country_code' => 'BD', 'country_name' => 'Bangladesh', 'currency_code' => 'BDT', 'currency_name' => 'Bangladeshi Taka', 'symbol' => '৳'],
            ['country_code' => 'BB', 'country_name' => 'Barbados', 'currency_code' => 'BBD', 'currency_name' => 'Barbadian Dollar', 'symbol' => '$'],
            ['country_code' => 'BY', 'country_name' => 'Belarus', 'currency_code' => 'BYN', 'currency_name' => 'Belarusian Ruble', 'symbol' => 'Br'],
            ['country_code' => 'BE', 'country_name' => 'Belgium', 'currency_code' => 'EUR', 'currency_name' => 'Euro', 'symbol' => '€'],
            ['country_code' => 'BZ', 'country_name' => 'Belize', 'currency_code' => 'BZD', 'currency_name' => 'Belize Dollar', 'symbol' => '$'],
            ['country_code' => 'BJ', 'country_name' => 'Benin', 'currency_code' => 'XOF', 'currency_name' => 'West African CFA Franc', 'symbol' => 'CFA'],
            ['country_code' => 'BT', 'country_name' => 'Bhutan', 'currency_code' => 'BTN', 'currency_name' => 'Bhutanese Ngultrum', 'symbol' => 'Nu.'],
            ['country_code' => 'BO', 'country_name' => 'Bolivia', 'currency_code' => 'BOB', 'currency_name' => 'Bolivian Boliviano', 'symbol' => 'Bs.'],
            ['country_code' => 'BA', 'country_name' => 'Bosnia and Herzegovina', 'currency_code' => 'BAM', 'currency_name' => 'Bosnia and Herzegovina Convertible Mark', 'symbol' => 'KM'],
            ['country_code' => 'BW', 'country_name' => 'Botswana', 'currency_code' => 'BWP', 'currency_name' => 'Botswana Pula', 'symbol' => 'P'],
            ['country_code' => 'BR', 'country_name' => 'Brazil', 'currency_code' => 'BRL', 'currency_name' => 'Brazilian Real', 'symbol' => 'R$'],
            ['country_code' => 'BN', 'country_name' => 'Brunei', 'currency_code' => 'BND', 'currency_name' => 'Brunei Dollar', 'symbol' => '$'],
            ['country_code' => 'BG', 'country_name' => 'Bulgaria', 'currency_code' => 'BGN', 'currency_name' => 'Bulgarian Lev', 'symbol' => 'лв'],
            ['country_code' => 'BF', 'country_name' => 'Burkina Faso', 'currency_code' => 'XOF', 'currency_name' => 'West African CFA Franc', 'symbol' => 'CFA'],
            ['country_code' => 'BI', 'country_name' => 'Burundi', 'currency_code' => 'BIF', 'currency_name' => 'Burundian Franc', 'symbol' => 'FBu'],

            ['country_code' => 'CV', 'country_name' => 'Cabo Verde', 'currency_code' => 'CVE', 'currency_name' => 'Cape Verdean Escudo', 'symbol' => '$'],
            ['country_code' => 'KH', 'country_name' => 'Cambodia', 'currency_code' => 'KHR', 'currency_name' => 'Cambodian Riel', 'symbol' => '៛'],
            ['country_code' => 'CM', 'country_name' => 'Cameroon', 'currency_code' => 'XAF', 'currency_name' => 'Central African CFA Franc', 'symbol' => 'FCFA'],
            ['country_code' => 'CA', 'country_name' => 'Canada', 'currency_code' => 'CAD', 'currency_name' => 'Canadian Dollar', 'symbol' => '$'],
            ['country_code' => 'CF', 'country_name' => 'Central African Republic', 'currency_code' => 'XAF', 'currency_name' => 'Central African CFA Franc', 'symbol' => 'FCFA'],
            ['country_code' => 'TD', 'country_name' => 'Chad', 'currency_code' => 'XAF', 'currency_name' => 'Central African CFA Franc', 'symbol' => 'FCFA'],
            ['country_code' => 'CL', 'country_name' => 'Chile', 'currency_code' => 'CLP', 'currency_name' => 'Chilean Peso', 'symbol' => '$'],
            ['country_code' => 'CN', 'country_name' => 'China', 'currency_code' => 'CNY', 'currency_name' => 'Chinese Yuan', 'symbol' => '¥'],
            ['country_code' => 'CO', 'country_name' => 'Colombia', 'currency_code' => 'COP', 'currency_name' => 'Colombian Peso', 'symbol' => '$'],
            ['country_code' => 'KM', 'country_name' => 'Comoros', 'currency_code' => 'KMF', 'currency_name' => 'Comorian Franc', 'symbol' => 'CF'],
            ['country_code' => 'CG', 'country_name' => 'Republic of the Congo', 'currency_code' => 'XAF', 'currency_name' => 'Central African CFA Franc', 'symbol' => 'FCFA'],
            ['country_code' => 'CD', 'country_name' => 'Democratic Republic of the Congo', 'currency_code' => 'CDF', 'currency_name' => 'Congolese Franc', 'symbol' => 'FC'],
            ['country_code' => 'CR', 'country_name' => 'Costa Rica', 'currency_code' => 'CRC', 'currency_name' => 'Costa Rican Colón', 'symbol' => '₡'],
            ['country_code' => 'CI', 'country_name' => 'Côte d’Ivoire', 'currency_code' => 'XOF', 'currency_name' => 'West African CFA Franc', 'symbol' => 'CFA'],
            ['country_code' => 'HR', 'country_name' => 'Croatia', 'currency_code' => 'EUR', 'currency_name' => 'Euro', 'symbol' => '€'],
            ['country_code' => 'CU', 'country_name' => 'Cuba', 'currency_code' => 'CUP', 'currency_name' => 'Cuban Peso', 'symbol' => '$'],
            ['country_code' => 'CY', 'country_name' => 'Cyprus', 'currency_code' => 'EUR', 'currency_name' => 'Euro', 'symbol' => '€'],
            ['country_code' => 'CZ', 'country_name' => 'Czechia', 'currency_code' => 'CZK', 'currency_name' => 'Czech Koruna', 'symbol' => 'Kč'],

            ['country_code' => 'DK', 'country_name' => 'Denmark', 'currency_code' => 'DKK', 'currency_name' => 'Danish Krone', 'symbol' => 'kr'],
            ['country_code' => 'DJ', 'country_name' => 'Djibouti', 'currency_code' => 'DJF', 'currency_name' => 'Djiboutian Franc', 'symbol' => 'Fdj'],
            ['country_code' => 'DM', 'country_name' => 'Dominica', 'currency_code' => 'XCD', 'currency_name' => 'East Caribbean Dollar', 'symbol' => '$'],
            ['country_code' => 'DO', 'country_name' => 'Dominican Republic', 'currency_code' => 'DOP', 'currency_name' => 'Dominican Peso', 'symbol' => 'RD$'],

            ['country_code' => 'EC', 'country_name' => 'Ecuador', 'currency_code' => 'USD', 'currency_name' => 'United States Dollar', 'symbol' => '$'],
            ['country_code' => 'EG', 'country_name' => 'Egypt', 'currency_code' => 'EGP', 'currency_name' => 'Egyptian Pound', 'symbol' => 'E£'],
            ['country_code' => 'SV', 'country_name' => 'El Salvador', 'currency_code' => 'USD', 'currency_name' => 'United States Dollar', 'symbol' => '$'],
            ['country_code' => 'GQ', 'country_name' => 'Equatorial Guinea', 'currency_code' => 'XAF', 'currency_name' => 'Central African CFA Franc', 'symbol' => 'FCFA'],
            ['country_code' => 'ER', 'country_name' => 'Eritrea', 'currency_code' => 'ERN', 'currency_name' => 'Eritrean Nakfa', 'symbol' => 'Nfk'],
            ['country_code' => 'EE', 'country_name' => 'Estonia', 'currency_code' => 'EUR', 'currency_name' => 'Euro', 'symbol' => '€'],
            ['country_code' => 'SZ', 'country_name' => 'Eswatini', 'currency_code' => 'SZL', 'currency_name' => 'Swazi Lilangeni', 'symbol' => 'L'],
            ['country_code' => 'ET', 'country_name' => 'Ethiopia', 'currency_code' => 'ETB', 'currency_name' => 'Ethiopian Birr', 'symbol' => 'Br'],

            ['country_code' => 'FJ', 'country_name' => 'Fiji', 'currency_code' => 'FJD', 'currency_name' => 'Fijian Dollar', 'symbol' => '$'],
            ['country_code' => 'FI', 'country_name' => 'Finland', 'currency_code' => 'EUR', 'currency_name' => 'Euro', 'symbol' => '€'],
            ['country_code' => 'FR', 'country_name' => 'France', 'currency_code' => 'EUR', 'currency_name' => 'Euro', 'symbol' => '€'],

            ['country_code' => 'GA', 'country_name' => 'Gabon', 'currency_code' => 'XAF', 'currency_name' => 'Central African CFA Franc', 'symbol' => 'FCFA'],
            ['country_code' => 'GM', 'country_name' => 'Gambia', 'currency_code' => 'GMD', 'currency_name' => 'Gambian Dalasi', 'symbol' => 'D'],
            ['country_code' => 'GE', 'country_name' => 'Georgia', 'currency_code' => 'GEL', 'currency_name' => 'Georgian Lari', 'symbol' => '₾'],
            ['country_code' => 'DE', 'country_name' => 'Germany', 'currency_code' => 'EUR', 'currency_name' => 'Euro', 'symbol' => '€'],
            ['country_code' => 'GH', 'country_name' => 'Ghana', 'currency_code' => 'GHS', 'currency_name' => 'Ghanaian Cedi', 'symbol' => '₵'],
            ['country_code' => 'GR', 'country_name' => 'Greece', 'currency_code' => 'EUR', 'currency_name' => 'Euro', 'symbol' => '€'],
            ['country_code' => 'GD', 'country_name' => 'Grenada', 'currency_code' => 'XCD', 'currency_name' => 'East Caribbean Dollar', 'symbol' => '$'],
            ['country_code' => 'GT', 'country_name' => 'Guatemala', 'currency_code' => 'GTQ', 'currency_name' => 'Guatemalan Quetzal', 'symbol' => 'Q'],
            ['country_code' => 'GN', 'country_name' => 'Guinea', 'currency_code' => 'GNF', 'currency_name' => 'Guinean Franc', 'symbol' => 'FG'],
            ['country_code' => 'GW', 'country_name' => 'Guinea-Bissau', 'currency_code' => 'XOF', 'currency_name' => 'West African CFA Franc', 'symbol' => 'CFA'],
            ['country_code' => 'GY', 'country_name' => 'Guyana', 'currency_code' => 'GYD', 'currency_name' => 'Guyanese Dollar', 'symbol' => '$'],

            ['country_code' => 'HT', 'country_name' => 'Haiti', 'currency_code' => 'HTG', 'currency_name' => 'Haitian Gourde', 'symbol' => 'G'],
            ['country_code' => 'HN', 'country_name' => 'Honduras', 'currency_code' => 'HNL', 'currency_name' => 'Honduran Lempira', 'symbol' => 'L'],
            ['country_code' => 'HU', 'country_name' => 'Hungary', 'currency_code' => 'HUF', 'currency_name' => 'Hungarian Forint', 'symbol' => 'Ft'],

            ['country_code' => 'IS', 'country_name' => 'Iceland', 'currency_code' => 'ISK', 'currency_name' => 'Icelandic Króna', 'symbol' => 'kr'],
            ['country_code' => 'IN', 'country_name' => 'India', 'currency_code' => 'INR', 'currency_name' => 'Indian Rupee', 'symbol' => '₹'],
            ['country_code' => 'ID', 'country_name' => 'Indonesia', 'currency_code' => 'IDR', 'currency_name' => 'Indonesian Rupiah', 'symbol' => 'Rp'],
            ['country_code' => 'IR', 'country_name' => 'Iran', 'currency_code' => 'IRR', 'currency_name' => 'Iranian Rial', 'symbol' => '﷼'],
            ['country_code' => 'IQ', 'country_name' => 'Iraq', 'currency_code' => 'IQD', 'currency_name' => 'Iraqi Dinar', 'symbol' => 'ع.د'],
            ['country_code' => 'IE', 'country_name' => 'Ireland', 'currency_code' => 'EUR', 'currency_name' => 'Euro', 'symbol' => '€'],
            ['country_code' => 'IL', 'country_name' => 'Israel', 'currency_code' => 'ILS', 'currency_name' => 'Israeli New Shekel', 'symbol' => '₪'],
            ['country_code' => 'IT', 'country_name' => 'Italy', 'currency_code' => 'EUR', 'currency_name' => 'Euro', 'symbol' => '€'],

            ['country_code' => 'JM', 'country_name' => 'Jamaica', 'currency_code' => 'JMD', 'currency_name' => 'Jamaican Dollar', 'symbol' => '$'],
            ['country_code' => 'JP', 'country_name' => 'Japan', 'currency_code' => 'JPY', 'currency_name' => 'Japanese Yen', 'symbol' => '¥'],
            ['country_code' => 'JO', 'country_name' => 'Jordan', 'currency_code' => 'JOD', 'currency_name' => 'Jordanian Dinar', 'symbol' => 'د.ا'],

            ['country_code' => 'KZ', 'country_name' => 'Kazakhstan', 'currency_code' => 'KZT', 'currency_name' => 'Kazakhstani Tenge', 'symbol' => '₸'],
            ['country_code' => 'KE', 'country_name' => 'Kenya', 'currency_code' => 'KES', 'currency_name' => 'Kenyan Shilling', 'symbol' => 'KSh'],
            ['country_code' => 'KI', 'country_name' => 'Kiribati', 'currency_code' => 'AUD', 'currency_name' => 'Australian Dollar', 'symbol' => '$'],
            ['country_code' => 'KP', 'country_name' => 'North Korea', 'currency_code' => 'KPW', 'currency_name' => 'North Korean Won', 'symbol' => '₩'],
            ['country_code' => 'KR', 'country_name' => 'South Korea', 'currency_code' => 'KRW', 'currency_name' => 'South Korean Won', 'symbol' => '₩'],
            ['country_code' => 'KW', 'country_name' => 'Kuwait', 'currency_code' => 'KWD', 'currency_name' => 'Kuwaiti Dinar', 'symbol' => 'د.ك'],
            ['country_code' => 'KG', 'country_name' => 'Kyrgyzstan', 'currency_code' => 'KGS', 'currency_name' => 'Kyrgyzstani Som', 'symbol' => 'с'],

            ['country_code' => 'LA', 'country_name' => 'Laos', 'currency_code' => 'LAK', 'currency_name' => 'Lao Kip', 'symbol' => '₭'],
            ['country_code' => 'LV', 'country_name' => 'Latvia', 'currency_code' => 'EUR', 'currency_name' => 'Euro', 'symbol' => '€'],
            ['country_code' => 'LB', 'country_name' => 'Lebanon', 'currency_code' => 'LBP', 'currency_name' => 'Lebanese Pound', 'symbol' => 'ل.ل'],
            ['country_code' => 'LS', 'country_name' => 'Lesotho', 'currency_code' => 'LSL', 'currency_name' => 'Lesotho Loti', 'symbol' => 'L'],
            ['country_code' => 'LR', 'country_name' => 'Liberia', 'currency_code' => 'LRD', 'currency_name' => 'Liberian Dollar', 'symbol' => '$'],
            ['country_code' => 'LY', 'country_name' => 'Libya', 'currency_code' => 'LYD', 'currency_name' => 'Libyan Dinar', 'symbol' => 'ل.د'],
            ['country_code' => 'LI', 'country_name' => 'Liechtenstein', 'currency_code' => 'CHF', 'currency_name' => 'Swiss Franc', 'symbol' => 'CHF'],
            ['country_code' => 'LT', 'country_name' => 'Lithuania', 'currency_code' => 'EUR', 'currency_name' => 'Euro', 'symbol' => '€'],
            ['country_code' => 'LU', 'country_name' => 'Luxembourg', 'currency_code' => 'EUR', 'currency_name' => 'Euro', 'symbol' => '€'],

            ['country_code' => 'MG', 'country_name' => 'Madagascar', 'currency_code' => 'MGA', 'currency_name' => 'Malagasy Ariary', 'symbol' => 'Ar'],
            ['country_code' => 'MW', 'country_name' => 'Malawi', 'currency_code' => 'MWK', 'currency_name' => 'Malawian Kwacha', 'symbol' => 'MK'],
            ['country_code' => 'MY', 'country_name' => 'Malaysia', 'currency_code' => 'MYR', 'currency_name' => 'Malaysian Ringgit', 'symbol' => 'RM'],
            ['country_code' => 'MV', 'country_name' => 'Maldives', 'currency_code' => 'MVR', 'currency_name' => 'Maldivian Rufiyaa', 'symbol' => 'Rf'],
            ['country_code' => 'ML', 'country_name' => 'Mali', 'currency_code' => 'XOF', 'currency_name' => 'West African CFA Franc', 'symbol' => 'CFA'],
            ['country_code' => 'MT', 'country_name' => 'Malta', 'currency_code' => 'EUR', 'currency_name' => 'Euro', 'symbol' => '€'],
            ['country_code' => 'MH', 'country_name' => 'Marshall Islands', 'currency_code' => 'USD', 'currency_name' => 'United States Dollar', 'symbol' => '$'],
            ['country_code' => 'MR', 'country_name' => 'Mauritania', 'currency_code' => 'MRU', 'currency_name' => 'Mauritanian Ouguiya', 'symbol' => 'UM'],
            ['country_code' => 'MU', 'country_name' => 'Mauritius', 'currency_code' => 'MUR', 'currency_name' => 'Mauritian Rupee', 'symbol' => '₨'],
            ['country_code' => 'MX', 'country_name' => 'Mexico', 'currency_code' => 'MXN', 'currency_name' => 'Mexican Peso', 'symbol' => '$'],
            ['country_code' => 'FM', 'country_name' => 'Micronesia', 'currency_code' => 'USD', 'currency_name' => 'United States Dollar', 'symbol' => '$'],
            ['country_code' => 'MD', 'country_name' => 'Moldova', 'currency_code' => 'MDL', 'currency_name' => 'Moldovan Leu', 'symbol' => 'L'],
            ['country_code' => 'MC', 'country_name' => 'Monaco', 'currency_code' => 'EUR', 'currency_name' => 'Euro', 'symbol' => '€'],
            ['country_code' => 'MN', 'country_name' => 'Mongolia', 'currency_code' => 'MNT', 'currency_name' => 'Mongolian Tögrög', 'symbol' => '₮'],
            ['country_code' => 'ME', 'country_name' => 'Montenegro', 'currency_code' => 'EUR', 'currency_name' => 'Euro', 'symbol' => '€'],
            ['country_code' => 'MA', 'country_name' => 'Morocco', 'currency_code' => 'MAD', 'currency_name' => 'Moroccan Dirham', 'symbol' => 'د.م.'],
            ['country_code' => 'MZ', 'country_name' => 'Mozambique', 'currency_code' => 'MZN', 'currency_name' => 'Mozambican Metical', 'symbol' => 'MT'],
            ['country_code' => 'MM', 'country_name' => 'Myanmar', 'currency_code' => 'MMK', 'currency_name' => 'Myanmar Kyat', 'symbol' => 'K'],

            ['country_code' => 'NA', 'country_name' => 'Namibia', 'currency_code' => 'NAD', 'currency_name' => 'Namibian Dollar', 'symbol' => '$'],
            ['country_code' => 'NR', 'country_name' => 'Nauru', 'currency_code' => 'AUD', 'currency_name' => 'Australian Dollar', 'symbol' => '$'],
            ['country_code' => 'NP', 'country_name' => 'Nepal', 'currency_code' => 'NPR', 'currency_name' => 'Nepalese Rupee', 'symbol' => '₨'],
            ['country_code' => 'NL', 'country_name' => 'Netherlands', 'currency_code' => 'EUR', 'currency_name' => 'Euro', 'symbol' => '€'],
            ['country_code' => 'NZ', 'country_name' => 'New Zealand', 'currency_code' => 'NZD', 'currency_name' => 'New Zealand Dollar', 'symbol' => '$'],
            ['country_code' => 'NI', 'country_name' => 'Nicaragua', 'currency_code' => 'NIO', 'currency_name' => 'Nicaraguan Córdoba', 'symbol' => 'C$'],
            ['country_code' => 'NE', 'country_name' => 'Niger', 'currency_code' => 'XOF', 'currency_name' => 'West African CFA Franc', 'symbol' => 'CFA'],
            ['country_code' => 'NG', 'country_name' => 'Nigeria', 'currency_code' => 'NGN', 'currency_name' => 'Nigerian Naira', 'symbol' => '₦'],
            ['country_code' => 'MK', 'country_name' => 'North Macedonia', 'currency_code' => 'MKD', 'currency_name' => 'Macedonian Denar', 'symbol' => 'ден'],
            ['country_code' => 'NO', 'country_name' => 'Norway', 'currency_code' => 'NOK', 'currency_name' => 'Norwegian Krone', 'symbol' => 'kr'],

            ['country_code' => 'OM', 'country_name' => 'Oman', 'currency_code' => 'OMR', 'currency_name' => 'Omani Rial', 'symbol' => 'ر.ع.'],

            ['country_code' => 'PK', 'country_name' => 'Pakistan', 'currency_code' => 'PKR', 'currency_name' => 'Pakistani Rupee', 'symbol' => '₨'],
            ['country_code' => 'PW', 'country_name' => 'Palau', 'currency_code' => 'USD', 'currency_name' => 'United States Dollar', 'symbol' => '$'],
            ['country_code' => 'PA', 'country_name' => 'Panama', 'currency_code' => 'PAB', 'currency_name' => 'Panamanian Balboa', 'symbol' => 'B/.'],
            ['country_code' => 'PG', 'country_name' => 'Papua New Guinea', 'currency_code' => 'PGK', 'currency_name' => 'Papua New Guinean Kina', 'symbol' => 'K'],
            ['country_code' => 'PY', 'country_name' => 'Paraguay', 'currency_code' => 'PYG', 'currency_name' => 'Paraguayan Guaraní', 'symbol' => '₲'],
            ['country_code' => 'PE', 'country_name' => 'Peru', 'currency_code' => 'PEN', 'currency_name' => 'Peruvian Sol', 'symbol' => 'S/'],
            ['country_code' => 'PH', 'country_name' => 'Philippines', 'currency_code' => 'PHP', 'currency_name' => 'Philippine Peso', 'symbol' => '₱'],
            ['country_code' => 'PL', 'country_name' => 'Poland', 'currency_code' => 'PLN', 'currency_name' => 'Polish Złoty', 'symbol' => 'zł'],
            ['country_code' => 'PT', 'country_name' => 'Portugal', 'currency_code' => 'EUR', 'currency_name' => 'Euro', 'symbol' => '€'],

            ['country_code' => 'QA', 'country_name' => 'Qatar', 'currency_code' => 'QAR', 'currency_name' => 'Qatari Riyal', 'symbol' => 'ر.ق'],

            ['country_code' => 'RO', 'country_name' => 'Romania', 'currency_code' => 'RON', 'currency_name' => 'Romanian Leu', 'symbol' => 'lei'],
            ['country_code' => 'RU', 'country_name' => 'Russia', 'currency_code' => 'RUB', 'currency_name' => 'Russian Ruble', 'symbol' => '₽'],
            ['country_code' => 'RW', 'country_name' => 'Rwanda', 'currency_code' => 'RWF', 'currency_name' => 'Rwandan Franc', 'symbol' => 'FRw'],

            ['country_code' => 'KN', 'country_name' => 'Saint Kitts and Nevis', 'currency_code' => 'XCD', 'currency_name' => 'East Caribbean Dollar', 'symbol' => '$'],
            ['country_code' => 'LC', 'country_name' => 'Saint Lucia', 'currency_code' => 'XCD', 'currency_name' => 'East Caribbean Dollar', 'symbol' => '$'],
            ['country_code' => 'VC', 'country_name' => 'Saint Vincent and the Grenadines', 'currency_code' => 'XCD', 'currency_name' => 'East Caribbean Dollar', 'symbol' => '$'],
            ['country_code' => 'WS', 'country_name' => 'Samoa', 'currency_code' => 'WST', 'currency_name' => 'Samoan Tala', 'symbol' => 'T'],
            ['country_code' => 'SM', 'country_name' => 'San Marino', 'currency_code' => 'EUR', 'currency_name' => 'Euro', 'symbol' => '€'],
            ['country_code' => 'ST', 'country_name' => 'São Tomé and Príncipe', 'currency_code' => 'STN', 'currency_name' => 'São Tomé and Príncipe Dobra', 'symbol' => 'Db'],
            ['country_code' => 'SA', 'country_name' => 'Saudi Arabia', 'currency_code' => 'SAR', 'currency_name' => 'Saudi Riyal', 'symbol' => '﷼'],
            ['country_code' => 'SN', 'country_name' => 'Senegal', 'currency_code' => 'XOF', 'currency_name' => 'West African CFA Franc', 'symbol' => 'CFA'],
            ['country_code' => 'RS', 'country_name' => 'Serbia', 'currency_code' => 'RSD', 'currency_name' => 'Serbian Dinar', 'symbol' => 'дин'],
            ['country_code' => 'SC', 'country_name' => 'Seychelles', 'currency_code' => 'SCR', 'currency_name' => 'Seychellois Rupee', 'symbol' => '₨'],
            ['country_code' => 'SL', 'country_name' => 'Sierra Leone', 'currency_code' => 'SLE', 'currency_name' => 'Sierra Leonean Leone', 'symbol' => 'Le'],
            ['country_code' => 'SG', 'country_name' => 'Singapore', 'currency_code' => 'SGD', 'currency_name' => 'Singapore Dollar', 'symbol' => '$'],
            ['country_code' => 'SK', 'country_name' => 'Slovakia', 'currency_code' => 'EUR', 'currency_name' => 'Euro', 'symbol' => '€'],
            ['country_code' => 'SI', 'country_name' => 'Slovenia', 'currency_code' => 'EUR', 'currency_name' => 'Euro', 'symbol' => '€'],
            ['country_code' => 'SB', 'country_name' => 'Solomon Islands', 'currency_code' => 'SBD', 'currency_name' => 'Solomon Islands Dollar', 'symbol' => '$'],
            ['country_code' => 'SO', 'country_name' => 'Somalia', 'currency_code' => 'SOS', 'currency_name' => 'Somali Shilling', 'symbol' => 'Sh'],
            ['country_code' => 'ZA', 'country_name' => 'South Africa', 'currency_code' => 'ZAR', 'currency_name' => 'South African Rand', 'symbol' => 'R'],
            ['country_code' => 'SS', 'country_name' => 'South Sudan', 'currency_code' => 'SSP', 'currency_name' => 'South Sudanese Pound', 'symbol' => '£'],
            ['country_code' => 'ES', 'country_name' => 'Spain', 'currency_code' => 'EUR', 'currency_name' => 'Euro', 'symbol' => '€'],
            ['country_code' => 'LK', 'country_name' => 'Sri Lanka', 'currency_code' => 'LKR', 'currency_name' => 'Sri Lankan Rupee', 'symbol' => 'Rs'],
            ['country_code' => 'SD', 'country_name' => 'Sudan', 'currency_code' => 'SDG', 'currency_name' => 'Sudanese Pound', 'symbol' => 'ج.س.'],
            ['country_code' => 'SR', 'country_name' => 'Suriname', 'currency_code' => 'SRD', 'currency_name' => 'Surinamese Dollar', 'symbol' => '$'],
            ['country_code' => 'SE', 'country_name' => 'Sweden', 'currency_code' => 'SEK', 'currency_name' => 'Swedish Krona', 'symbol' => 'kr'],
            ['country_code' => 'CH', 'country_name' => 'Switzerland', 'currency_code' => 'CHF', 'currency_name' => 'Swiss Franc', 'symbol' => 'CHF'],
            ['country_code' => 'SY', 'country_name' => 'Syria', 'currency_code' => 'SYP', 'currency_name' => 'Syrian Pound', 'symbol' => '£'],

            ['country_code' => 'TJ', 'country_name' => 'Tajikistan', 'currency_code' => 'TJS', 'currency_name' => 'Tajikistani Somoni', 'symbol' => 'ЅМ'],
            ['country_code' => 'TZ', 'country_name' => 'Tanzania', 'currency_code' => 'TZS', 'currency_name' => 'Tanzanian Shilling', 'symbol' => 'TSh'],
            ['country_code' => 'TH', 'country_name' => 'Thailand', 'currency_code' => 'THB', 'currency_name' => 'Thai Baht', 'symbol' => '฿'],
            ['country_code' => 'TL', 'country_name' => 'Timor-Leste', 'currency_code' => 'USD', 'currency_name' => 'United States Dollar', 'symbol' => '$'],
            ['country_code' => 'TG', 'country_name' => 'Togo', 'currency_code' => 'XOF', 'currency_name' => 'West African CFA Franc', 'symbol' => 'CFA'],
            ['country_code' => 'TO', 'country_name' => 'Tonga', 'currency_code' => 'TOP', 'currency_name' => 'Tongan Paʻanga', 'symbol' => 'T$'],
            ['country_code' => 'TT', 'country_name' => 'Trinidad and Tobago', 'currency_code' => 'TTD', 'currency_name' => 'Trinidad and Tobago Dollar', 'symbol' => '$'],
            ['country_code' => 'TN', 'country_name' => 'Tunisia', 'currency_code' => 'TND', 'currency_name' => 'Tunisian Dinar', 'symbol' => 'د.ت'],
            ['country_code' => 'TR', 'country_name' => 'Türkiye', 'currency_code' => 'TRY', 'currency_name' => 'Turkish Lira', 'symbol' => '₺'],
            ['country_code' => 'TM', 'country_name' => 'Turkmenistan', 'currency_code' => 'TMT', 'currency_name' => 'Turkmenistan Manat', 'symbol' => 'm'],
            ['country_code' => 'TV', 'country_name' => 'Tuvalu', 'currency_code' => 'AUD', 'currency_name' => 'Australian Dollar', 'symbol' => '$'],

            ['country_code' => 'UG', 'country_name' => 'Uganda', 'currency_code' => 'UGX', 'currency_name' => 'Ugandan Shilling', 'symbol' => 'USh'],
            ['country_code' => 'UA', 'country_name' => 'Ukraine', 'currency_code' => 'UAH', 'currency_name' => 'Ukrainian Hryvnia', 'symbol' => '₴'],
            ['country_code' => 'AE', 'country_name' => 'United Arab Emirates', 'currency_code' => 'AED', 'currency_name' => 'UAE Dirham', 'symbol' => 'د.إ'],
            ['country_code' => 'GB', 'country_name' => 'United Kingdom', 'currency_code' => 'GBP', 'currency_name' => 'British Pound Sterling', 'symbol' => '£'],
            ['country_code' => 'US', 'country_name' => 'United States', 'currency_code' => 'USD', 'currency_name' => 'United States Dollar', 'symbol' => '$'],
            ['country_code' => 'UY', 'country_name' => 'Uruguay', 'currency_code' => 'UYU', 'currency_name' => 'Uruguayan Peso', 'symbol' => '$U'],
            ['country_code' => 'UZ', 'country_name' => 'Uzbekistan', 'currency_code' => 'UZS', 'currency_name' => 'Uzbekistani Som', 'symbol' => 'soʻm'],

            ['country_code' => 'VU', 'country_name' => 'Vanuatu', 'currency_code' => 'VUV', 'currency_name' => 'Vanuatu Vatu', 'symbol' => 'VT'],
            ['country_code' => 'VA', 'country_name' => 'Vatican City', 'currency_code' => 'EUR', 'currency_name' => 'Euro', 'symbol' => '€'],
            ['country_code' => 'VE', 'country_name' => 'Venezuela', 'currency_code' => 'VES', 'currency_name' => 'Venezuelan Bolívar', 'symbol' => 'Bs.'],
            ['country_code' => 'VN', 'country_name' => 'Vietnam', 'currency_code' => 'VND', 'currency_name' => 'Vietnamese Đồng', 'symbol' => '₫'],

            ['country_code' => 'YE', 'country_name' => 'Yemen', 'currency_code' => 'YER', 'currency_name' => 'Yemeni Rial', 'symbol' => '﷼'],

            ['country_code' => 'ZM', 'country_name' => 'Zambia', 'currency_code' => 'ZMW', 'currency_name' => 'Zambian Kwacha', 'symbol' => 'ZK'],
            ['country_code' => 'ZW', 'country_name' => 'Zimbabwe', 'currency_code' => 'ZWG', 'currency_name' => 'Zimbabwe Gold', 'symbol' => 'ZiG'],
        ];

        DB::table('currencies')->upsert(
            $currencies,
            ['country_code'],
            ['country_name', 'currency_code', 'currency_name', 'symbol']
        );
    }
}